config/routes.rb
Rails.application.routes.draw do

  root 'sessions#new'

  get '/login',     to: 'sessions#new'
  post '/login',    to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  resources :posts, only: [:new, :create, :show, :index]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  
  validates :user_id, presence: true
  validates :title,   presence: true,
                      length: { minimum: 5 }
  validates :body,    presence: true,
                      length: { minimum: 5 }
  
  attr_accessor :user_id
  
  def author
    User.find_by(user_id).name
  end
  
end

app/models/user.rb
class User < ApplicationRecord

	attr_accessor :remember_token

	before_save 	:downcase_email

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  
  validates :name,  presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX }
  
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

	# Creates a hash digest of the given string.
	def User.digest(string)
		BCrypt::Password.create(string)
	end

	# Creates a random urlsafe token.
	def User.new_token
		SecureRandom.urlsafe_base64
	end

	# Gives the user a remember token and digest.
	def remember_user
		self.remember_token = User.new_token
		update_attribute(:remember_digest, User.digest(remember_token))
	end

	private

		# Changes the user's email to all lower-case.
		def downcase_email
			email.downcase!
		end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
	include SessionsHelper
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  before_action :user_signed_in, only: [:new, :create]
  
  def new
    @post = Post.new
  end
  
  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to posts_url
    end
  end
  
  def index
    @posts = Post.all
  end
  
  def show
    @post = Post.find(params[:id])
  end
  
  private
  
  def user_signed_in
    unless logged_in?
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end
  
  def post_params
    params.require(:post).permit(:user_id, :title, :body)
  end
    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by(email: params[:session][:email].downcase)
  	if user && user.authenticate(params[:session][:password])
  		log_in user
      redirect_to new_post_path
  	else
  		flash[:warning] = "Invalid login."
  		render 'new'
  	end
  end

  def destroy
  	log_out if logged_in?
  	redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def log_in(user)
		session[:user_id] = user.id
	end

	def current_user
		if (user_id = session[:user_id])
			@current_user ||= User.find_by(id: user_id)
		elsif (user_id = cookies.signed[:user_id])
			user = User.find_by(id: user_id)
			log_in user
			user.remember_user
			@current_user = user
		end
	end

	def logged_in?
		!current_user.nil?
	end

	def log_out
		session.delete(:user_id)
		cookies.delete(:user_id)
		@current_user = nil
	end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersOnly</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |message| %>
        <%= content_tag(:div, message) %>
    <% end %>

    <%= link_to "Sign in",  login_path  %>
    <%= link_to "Sign out", logout_path, method: :delete %>

    <%= yield %>
  </body>
</html>

app/views/posts/_post.html.erb
<li>
  <%= link_to post.title, post %>
</li>

app/views/posts/index.html.erb
<h1>All posts</h1>

<ul>
  <%= render @posts %>
</ul>

app/views/posts/new.html.erb
<%= form_for @post do |f| %>

  <%= f.label :title %><br />
  <%= f.text_field :title %><br />
  
  <%= f.label :body %><br />
  <%= f.text_area :body, size: "50x8" %><br />
  
  <%= f.submit("Create post") %>
  
  <%= f.hidden_field :user_id, value: session[:user_id] %>

<% end %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<% if logged_in? %>
  <h3><%= @post.author %></h3>
<% end %>
<p> <%= @post.body %></p>